# markdownlint-cli2 configuration
# Include both .md and .qmd files for Quarto support
globs:
  - "**/*.md"
  - "**/*.qmd"

# Exclude external and generated directories
ignores:
  - "devito_repo/**"
  - "venv/**"
  - ".venv/**"
  - "node_modules/**"
  - "_book/**"
  - "doc/pub/**"
  - "devito-plan.md"
