# This is a basic workflow to help you get started with Actions

name: Devito Book

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      DEVITO_ARCH: gcc-7
      DEVITO_LANGUAGE: "openmp"
      DEVITO_BACKEND: "core"
      PYTHON_VERSION: "3.7"

    strategy:
      # Prevent all build to stop if a single one fails
      fail-fast: false

    steps:
    - name: Checkout devito
      uses: actions/checkout@v1

    - name: Setup conda
      uses: goanpeca/setup-miniconda@v1
      with:
       activate-environment: devito
       environment-file: environment.yml
       python-version: 3.7
       auto-activate-base: false

    - name: Install dependencies
      # See setup-miniconda README, necessary to activate environment
      shell: bash -l {0}
      run: |
        pip install -e .
        pip install matplotlib
    - name: Tests in examples
      shell: bash -l {0}
      run: py.test --cov --cov-config=.coveragerc --cov-report=xml fdm-devito-notebooks/
